import type { Metadata } from "next";
import "../globals.css";
// import Navbar from "@/components/layout/navbar";
// import Footer from "@/components/layout/footer";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DasboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <>
      {/* <Navbar isLogged /> */}
      {children}
      {/* <Footer /> */}
    </>
  );
}
